// GENERATED by scripts/art/build_web_assets.py - do not edit by hand.
//
// The ten plots of public/art/campus/plate.png, as percentages of the
// plate so the screen never has to know its pixel size. Measured off the
// rendered plate rather than laid out on a grid: it is a hand-drawn town,
// and the plots vary by about 3%, so each tile is placed in its own rect.

import type { FacilityId } from './model'

/** The campus holds the nine buildable facilities AND the ground. The
 *  ground is not a FacilityId - it is levelled by capacity rather than by
 *  a board request - so the map carries it as its own member. */
export type CampusId = FacilityId | 'stadium'

export interface CampusPlot {
  /** which facility stands here */
  fid: CampusId
  /** the art folder the six tiles live in, which is not always the id:
   *  the pitch is drawn as 'playing-surface', the briefing room as
   *  'analysis'. Emitted rather than mapped in the screen so the names
   *  can only ever disagree in one place. */
  art: string
  /** percentages of the plate: left, top, width, height */
  x: number; y: number; w: number; h: number
}

/** Facilities draw larger than their plot so they read at map scale - the
 *  same 1.45 the reference composite uses. Centred, so the overspill is
 *  even and lands on the verge rather than the road. */
export const PLOT_OVERSIZE = 1.45

/** The ground is levelled by its seats rather than by a board request,
 *  so the map reads it straight off the club. The six grounds and the
 *  function that names them live in model.ts (GROUND_TIERS), which is
 *  also what the expansion ladder builds toward - one table, so the
 *  map can never disagree with the mechanic. */

export const CAMPUS_PLOTS: CampusPlot[] = [
  { fid: 'academy',     art: 'academy',         x:  8.840, y:  7.320, w: 12.063, h:  8.978 },
  { fid: 'paddock',     art: 'paddock',         x: 49.171, y: 15.331, w: 12.063, h:  8.978 },
  { fid: 'gym',         art: 'gym',             x:  7.919, y: 24.517, w: 12.155, h:  8.978 },
  { fid: 'kicking',     art: 'kicking',         x: 77.993, y: 27.417, w: 12.155, h:  9.047 },
  { fid: 'stadium',     art: 'stadium',         x: 43.370, y: 35.290, w: 12.155, h:  9.116 },
  { fid: 'pitch',       art: 'playing-surface', x: 65.654, y: 42.472, w: 12.431, h:  9.254 },
  { fid: 'recovery',    art: 'recovery',        x: 32.228, y: 53.384, w: 12.247, h:  9.185 },
  { fid: 'briefing',    art: 'analysis',        x:  6.446, y: 53.729, w: 12.431, h:  9.185 },
  { fid: 'shop',        art: 'shop',            x: 79.006, y: 60.359, w: 12.155, h:  9.116 },
  { fid: 'hospitality', art: 'hospitality',     x: 56.814, y: 63.122, w: 12.063, h:  9.047 },
]
