/**
 * ---- DOES THE WOMEN'S GAME CALL ITS PLAYERS "HE"? IN EVERY LANGUAGE ----
 *
 * Owner, 7 Sep: "double check language, cultural insensitive, gender
 * insensitive." And then: "do the french spanish and italian gendered
 * strings."
 *
 * The game had no gender-aware text of any kind, so every line written for the
 * men's game reached a women's career unchanged: "he was promised", "his
 * agent", "joueur", "lesionado". Every language now carries a feminine sibling
 * of a key where its text needs one (`key_f`, see i18n.ts setWorld) that t()
 * selects in a women's world - generated by scripts/tools/feminise.py and then
 * read and corrected by hand, with the corrections kept beside it.
 *
 * What this still counts is deliberate: the manager, the coaches, the scout,
 * the referee, a postman and a streaker keep their pronoun, because staff are
 * a coin in a women's world (gender.ts staffGender) and there is no per-person
 * string to pick. That is the design gap this number now measures.
 *
 * This plays real women's careers, IN THE WOMEN'S WORLD, in each language, and
 * reads what actually reaches the screen. It counts the masculine markers that
 * a regex can catch - pronouns, the player noun, the obvious adjectives - which
 * is the bulk of the problem and not all of it: a French past participle
 * agreeing with a masculine subject two clauses back is beyond a pattern, and
 * is why the strings are read by a person as well as counted by this.
 *
 * IT IS A REPORTER, NOT A GATE. It prints the number per language so the work
 * can be watched coming down, and lists the worst keys so it can be aimed.
 */
import { newGame, LEAGUE_DEFS } from '../src/game/newgame'
import { processWeekAndAdvance } from '../src/game/season'
import { newsBody, newsSubject } from '../src/game/model'
import { ensureLang, setLang, setWorld, type Lang } from '../src/game/i18n'

const MARKERS: Record<string, RegExp> = {
  en: /\b(he|him|his|himself|man|men|lad|lads|boy|boys|father|son|sons|brother|mr)\b/gi,
  // il/ils as subject, the noun, the obvious agreements. "lui" is left out: it
  // is the indirect object for both genders ("je lui parle") far more often
  // than it is the masculine stress pronoun.
  // "il y a", "il faut", "il reste" are impersonal and correct in any world -
  // counting them would report a problem the game does not have
  fr: /\b(il(?! (?:y|faut|faudra|faudrait|fallait|s'agit|reste|restera|restait|semble|paraît|vaut|pleut|suffit|convient|importe|manque|existe|arrive|se peut|fait|est (?:temps|possible|impossible|clair|vrai|rare|question|tard|tôt|encore|peu|trop)))|ils|joueur|joueurs|homme|hommes|garçon|garçons|celui|monsieur|blessé|blessés|fils|ce dernier)\b/gi,
  es: /\b(él|ellos|jugador|jugadores|hombre|hombres|chico|chicos|muchacho|muchachos|lesionado|lesionados|hijo|hijos|señor|titular)\b/gi,
  it: /\b(lui|egli|esso|giocatore|giocatori|uomo|uomini|ragazzo|ragazzi|infortunato|infortunati|figlio|figli|signor|titolare)\b/gi,
}

const LANGS = (process.argv[2] ? [process.argv[2]] : ['en', 'fr', 'es', 'it']) as Lang[]
const wClubs = LEAGUE_DEFS('w').flatMap(d => d.clubs).slice(0, 4).map(c => c.id)

// the careers are played ONCE and the news kept; then read in each language.
// Rendering is a pure function of the stored (k, v), so one set of careers is
// the same reading for all four, and the numbers are comparable.
const careers = wClubs.map((id, i) => {
  const g = newGame(id, 'Test', 500 + i * 7, undefined, 'coach', 'normal', 'w')
  for (let w = 0; w < 48 * 3; w++) processWeekAndAdvance(g)
  return g
})

setWorld('w')
const summary: string[] = []
for (const lang of LANGS) {
  await ensureLang(lang)
  setLang(lang)
  const MASC = MARKERS[lang]
  const seen = new Map<string, number>()
  const examples = new Map<string, string>()
  let lines = 0
  for (const g of careers) {
    for (const n of g.news) {
      for (const text of [newsSubject(n), newsBody(n)]) {
        if (!text) continue
        lines++
        const hits = text.match(MASC)
        if (!hits) continue
        const key = n.k ?? '(no key)'
        seen.set(key, (seen.get(key) ?? 0) + hits.length)
        if (!examples.has(key)) {
          MASC.lastIndex = 0
          const m = MASC.exec(text)
          MASC.lastIndex = 0
          const at = m?.index ?? 0
          examples.set(key, text.slice(Math.max(0, at - 45), at + 55).replace(/\n/g, ' '))
        }
      }
    }
  }
  const total = [...seen.values()].reduce((a, b) => a + b, 0)
  const worst = [...seen.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12)
  console.log(`\n=== ${lang}: a women's career, three seasons, four clubs ===`)
  console.log(`${lines} lines read; ${seen.size} stories carry a masculine marker; ${total} markers reached the screen`)
  for (const [k, c] of worst) {
    console.log(`  ${String(c).padStart(4)}x  ${k}`)
    console.log(`         ...${examples.get(k)}...`)
  }
  summary.push(`${lang} ${total} in ${seen.size} stories`)
}

console.log(`\nWOMEN'S VOICE REPORT: ${summary.join(' | ')}`)
console.log('This probe reports and never fails - see its header for why.')
